### ISSUE TITLE
Styles not getting applied

### ISSUE THREAD

**Issue by prashanth1k** [donotebase/quasar-tiptap#11]
Hello, 

Thanks for this extension - really makes my life easier :)

I am facing a problem using the package.  I followed the example on NPM / Codesandbox, but could not get styles to apply. See [this image](https://imgur.com/a/cwHlXsZ).

I get a series of errors complaining about the non-availability of components like `q-btn`, `q-list` etc.  Quasar does not import these automatically (with auto-import) since it does not "see" the components in my component? 

The errors are gone if I force Quasar to import components in `quasar.conf`..

`components: [
        "QBtn",
        "QIcon",
        "QTooltip",
        "QSeparator",
        "QInput",
        "QMenu",
        "QBtnDropdown"
      ],
`
But, the icons (even though I use `mdi-v5` do not show up in the menu bar. Am I missing anything?

**Comment by prashanth1k** [comment]
The documentation has to change.

Icons work correctly if "extras" section has 'material-icons' - not 'mdi-v5'.
```
extras: [
  'material-icons'
],
```

**Comment by mekery** [comment]
> The documentation has to change.
> 
> Icons work correctly if "extras" section has 'material-icons' - not 'mdi-v5'.
> 
> ```
> extras: [
>   'material-icons'
> ],
> ```

Thanks
