### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by dantrevino** [donotebase/quasar-tiptap#26]
I'm using quasar v1.12.13 and @quasar/app v2.0.6.  In my quasar.conf.js I had `importStrategy: 'auto'`, and when add quasar-tiptap, saw a ton of 'unknown custom element' errors.

Setting importStrategy to 'all' worked, but is less than ideal.

**Comment by larvanitis** [comment]
`importStrategy: 'auto'` works only for your own code, not for the dependencies imported from `node_modules`. As such, you will have to manually these to your `quasar.conf.js` > `framework`:

    components: [
      'QAvatar',
      'QBtn',
      'QBtnDropdown',
      'QIcon',
      'QInput',
      'QItem',
      'QItemLabel',
      'QItemSection',
      'QList',
      'QMenu',
      'QScrollArea',
      'QScrollObserver',
      'QSeparator',
      'QSpinner',
      'QTooltip',
    ],
    directives: ['ClosePopup'],
    plugins: ['AppFullscreen', 'Notify'],

**Comment by dantrevino** [comment]
Thanks for the info!
