### ISSUE TITLE
Regular space characters are being stripped from text input

### ISSUE THREAD

**Issue by viewfromthesky** [donotebase/quasar-tiptap#29]
Tested using quasar-tiptap 1.4.4 (tiptap 1.27.1/tiptap-extensions 1.29.1) and then 1.5.0 (tiptap 1.29.6/tiptap-extensions 1.32.5). Discovered as a bug that was only replicable on Firefox, but exists due to a difference in how Chrome and Firefox handle spacebar input. Chrome will input a non-breaking space, but Firefox will input a regular space character.

At the end of a string (your current input), any regular space characters that exist will be stripped as the next character is typed. When trying to paste a single space character at the end of a line, it will not commit in either browser. This behaviour is also replicable in the demo page you provide.

**Comment by viewfromthesky** [comment]
I don't believe this release actually has done it; the commit shows you added a new package and changed the `white-space` setup, but the HTML is still being trimmed so it's still not possible to add spaces at the end of a line. Specifically this is the output from `getHTML()`, as used in the example here:
```
  methods: {
    onUpdate ({ getJSON, getHTML }) {
      this.json = getJSON()
      this.html = getHTML()
      console.log('html', this.html)
    }
  }
```

If `onUpdate()` is called, it is normally called twice but, if you input a space character, it is called three times; once while returning the content with your space character and then another two more times without it.

**Comment by mekery** [comment]
> I don't believe this release actually has done it; the commit shows you added a new package and changed the `white-space` setup, but the HTML is still being trimmed so it's still not possible to add spaces at the end of a line. Specifically this is the output from `getHTML()`, as used in the example here:
> 
> ```
>   methods: {
>     onUpdate ({ getJSON, getHTML }) {
>       this.json = getJSON()
>       this.html = getHTML()
>       console.log('html', this.html)
>     }
>   }
> ```
> 
> If `onUpdate()` is called, it is normally called twice but, if you input a space character, it is called three times; once while returning the content with your space character and then another two more times without it.

Just realized that you replay after I closed this issue.
Would you try the latest release (1.7.0), I tested it and the space works as normal.

- [Demo](https://donotebase.github.io/quasar-tiptap)
