### ISSUE TITLE
Allow menububble to accept button props

### ISSUE THREAD

**Issue by joe-berg-colossus** [donotebase/quasar-tiptap#35]
Would be great to be able to customize the menu bubble with a variety of buttons.

**Comment by mekery** [comment]
You can use customized button

> Would be great to be able to customize the menu bubble with a variety of buttons.

There is a bubble property in options:

```
options: {
  ...,
  bubble: [
    'bold',
    'italic',
    'separator',
    'font-family',
    'fore-color',
    'back-color',
    'separator',
    'link',
    'separator',
    'align-group',
  ]
}
```

see [example](https://github.com/donotebase/quasar-tiptap/blob/dev/src/pages/examples/basic.vue)
