### ISSUE TITLE
Error: navigator is not defined when using in quasar SSR application. Force quasar-tiptap to run only on client side.

### ISSUE THREAD

**Issue by joe-berg-colossus** [donotebase/quasar-tiptap#36]
@mekery @icksky @larvanitis @qyloxe

Quasar application running in SSR mode.  

How can I get quasar-tiptap to run only on the client side?

When I directly access the page that uses the editor component I am getting the following error:
```
ReferenceError (500)
navigator is not defined
 
Open: myproject/node_modules/codemirror/lib/codemirror.js
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = global || self, global.CodeMirror = factory());
}(this, (function () { 'use strict';
 
  // Kludges for bugs and behavior differences that can't be feature
  // detected are enabled based on userAgent etc sniffing.
  var userAgent = navigator.userAgent;
  var platform = navigator.platform;
....
``` 

I installed the editor as a plugin like this:
`boot/tiptap.js'
```
// import something here
import Vue from "vue";
import { QuasarTiptapPlugin, RecommendedExtensions } from "quasar-tiptap";

// "async" is optional;
// more info on params: https://quasar.dev/quasar-cli/boot-files
export default async (/* { app, router, Vue ... } */) => {
  // something to do
  Vue.use(QuasarTiptapPlugin, {
    language: "en-us",
    spellcheck: true
  });
};
```

and my quasar.conf.js looks like this:
```
    boot: [
      'axios',
      { path: 'tiptap', server: false }
    ],

```

What am I missing?

**Comment by mekery** [comment]
@joe-berg-colossus 

I encountered same problem, and trying to find a way to work properly in SSR mode.

**Comment by joe-berg-colossus** [comment]
I figured out a solution. See below:

Create a boot file: quasar new boot tiptap

`tiptap.js`

```
import Vue from 'vue'
import { QuasarTiptapPlugin, RecommendedExtensions } from 'quasar-tiptap'
import "quasar-tiptap/lib/index.css";

Vue.use(QuasarTiptapPlugin, {
  language: 'en-us',
  spellcheck: true
})
```

reference boot file in quasar.conf.js and specify client only
```
 boot: [
  'axios',
  {path: 'tiptap', server: false} //render only on client
 ],
```

use component wherever you want in your application:
```
 <div>
  <quasar-tiptap
   ref="transcript"
   v-bind="options"
   @update="onUpdate"
  />
</div>
```

**Comment by mekery** [comment]
> I figured out a solution. See below:
> 
> Create a boot file: quasar new boot tiptap
> 
> `tiptap.js`
> 
> ```
> import Vue from 'vue'
> import { QuasarTiptapPlugin, RecommendedExtensions } from 'quasar-tiptap'
> import "quasar-tiptap/lib/index.css";
> 
> Vue.use(QuasarTiptapPlugin, {
>   language: 'en-us',
>   spellcheck: true
> })
> ```
> 
> reference boot file in quasar.conf.js and specify client only
> 
> ```
>  boot: [
>   'axios',
>   {path: 'tiptap', server: false} //render only on client
>  ],
> ```
> 
> use component wherever you want in your application:
> 
> ```
>  <div>
>   <quasar-tiptap
>    ref="transcript"
>    v-bind="options"
>    @update="onUpdate"
>   />
> </div>
> ```

Great, it works!
