### ISSUE TITLE
Custom extension

### ISSUE THREAD

**Issue by edgar-koster** [donotebase/quasar-tiptap#41]
How can I add my own custom extension to this component? I can add any which are listed in the readme but can't seem to import my own extension file without getting a message about `Error in data(): "TypeError: Class constructor Node cannot be invoked without 'new'"`

**Comment by edgar-koster** [comment]
I was able to solve this issue reverse enginering an existing extension

**Comment by neucassi** [comment]
@edgar-koster would you mind to provide a hint what the problem was?
