### ISSUE TITLE
Feature request: tableToolbar as property

### ISSUE THREAD

**Issue by edgar-koster** [donotebase/quasar-tiptap#46]
It would be nice to have the toolbar you get in edit mode of a table as a property. 

Right now I define a toolbar to look like:
![20210115-111004-chrome](https://user-images.githubusercontent.com/24190040/104717924-60404600-572a-11eb-8542-84af059908d4.png)

When clicking a table I get
![20210115-111022-chrome](https://user-images.githubusercontent.com/24190040/104717955-6df5cb80-572a-11eb-98b6-065256d449db.png)

But in fact I would like to be able to adjust it to my liking so you can do
![image](https://user-images.githubusercontent.com/24190040/104718102-a5647800-572a-11eb-8afe-9d8d0c73154e.png)

So what I've done is adjust the code of quasar-tiptap (pull request comming). I adjusted the basic layout too. To make it, I followed how `toolbar` is passed to the menubar. I now can pass `tableToolbar`. It defaults to the data which was already being used.

**Comment by mekery** [comment]
Great job, released in [1.8.0](https://github.com/donotebase/quasar-tiptap/compare/@1.7.0...@1.8.0)
